[package]
name = "Animate"
version = "0.1.0"
authors = ["wws <1274704958@qq.com>"]
edition = "2018"

[dependencies]
cgmath = "0.17"
console = "0.7.5"


[replace]
"rand:0.6.5" = { git = 'https://github.com/rust-random/rand', branch = '0.5' }