[package]
name = "Animate"
version = "0.1.0"
authors = ["wws <1274704958@qq.com>"]
edition = "2018"

[dependencies]
cgmath = "0.17"
console = "0.7.5"

[patch.crates-io]
rand = { git = 'https://github.com/rust-random/rand', tag= '0.6.5' }